# Generated by Django 3.1.4 on 2021-01-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_currency', models.CharField(max_length=10)),
                ('fiat_currency', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=24)),
                ('datetime_valid', models.DateTimeField(verbose_name='datetime valid')),
            ],
            options={
                'db_table': 'exchangerate',
            },
        ),
    ]
