# Generated by Django 3.2.5 on 2021-08-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['crypto_currency', 'fiat_currency', 'datetime_valid'], name='exchangerat_crypto__8e5f68_idx'),
        ),
    ]
