# Generated by Django 3.1.4 on 2020-12-26 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_currency', models.CharField(max_length=10)),
                ('amount_before_fee', models.DecimalField(decimal_places=10, max_digits=24)),
                ('amount_after_fee', models.DecimalField(decimal_places=10, max_digits=24)),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=24)),
                ('fiat_currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=24)),
                ('date_valid', models.DateTimeField(verbose_name='date transfered')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
