# Generated by Django 3.1.5 on 2021-02-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trade_id',
            field=models.CharField(default='MANUAL', max_length=20),
        ),
    ]
