# Generated by Django 3.2.2 on 2021-05-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20210511_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount_after_fee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount_before_fee',
        ),
    ]
