# Generated by Django 3.2.2 on 2021-05-11 20:30

import apps.transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20210511_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='crypto_amount',
            field=apps.transactions.models.NonscientificDecimalField(blank=True, decimal_places=10, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='crypto_fee',
            field=apps.transactions.models.NonscientificDecimalField(blank=True, decimal_places=10, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exchange_rate',
            field=apps.transactions.models.NonscientificDecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fiat_amount',
            field=apps.transactions.models.NonscientificDecimalField(blank=True, decimal_places=10, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fiat_fee',
            field=apps.transactions.models.NonscientificDecimalField(blank=True, decimal_places=10, max_digits=24, null=True),
        ),
    ]
