# Generated by Django 3.2.5 on 2021-08-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20210511_2230'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['crypto_currency', 'owner', 'transaction_type'], name='transaction_crypto__de924d_idx'),
        ),
    ]
